[phases.setup]
nixPkgs = ["python39", "postgresql_15"]
nixLibs = ["postgresql_15"]

[phases.install]
cmds = ["pip install -r back/requirements.txt"]

[phases.build]
cmds = ["cd back && python manage.py collectstatic --noinput"]

[start]
cmd = "bash railway_start.sh"
