# Generated by Django 4.2.29 on 2026-03-19 02:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('accredited', models.BooleanField(default=False)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('investment_type', models.CharField(choices=[('Fractional', 'Fractional Ownership'), ('Full', 'Full Ownership'), ('Development', 'Development Project'), ('REIT', 'Real Estate Investment Trust')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Funded', 'Fully Funded'), ('Closed', 'Closed'), ('Coming Soon', 'Coming Soon')], default='Active', max_length=50)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], default='Medium', max_length=20)),
                ('total_investment_needed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_annual_return', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('projected_appreciation', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('investment_term_months', models.IntegerField()),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('financial_projections', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_opportunities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Investment Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment_opportunities.investor')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment_opportunities.investmentopportunity')),
            ],
            options={
                'ordering': ['-investment_date'],
            },
        ),
    ]
